jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./csp-tech-teste  # 👈 ajuste para o caminho correto

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
